### ISSUE TITLE
Lab 2 - mapping data flows ex 5 task 3 step 6

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#82] opened 2021-05-15 21:11 UTC
when running the data flow, there is an error that states that a staging area needs to be set. Its not in the instructions, but I am assuming under Settings in that step, we select the data lake as the data source and the 'staging' container and leave the directory blank. (unless I did something wrong earlier). It ran after I put that in place, but I think I had another problem because it kicked back a failed attempt

**Comment by VitalyMCT** [comment] 2021-05-18 23:06
Confirmed - definitely an issue with instructions here. Need to define and use linked service for staging.

Something like this:

![image](https://user-images.githubusercontent.com/1765732/118734366-114b1000-b7f3-11eb-9516-37fdfceb864c.png)

**Comment by Jason-M-Richards** [comment] 2021-05-21 13:35
I haven’t heard back regarding this particular issue so I hope something is getting resolved, but it could have been user error I suppose.

**Comment by joelhulen** [comment] 2021-05-21 14:09
It appears as though you missed a step in Exercise 5, Task 2, step 36 (https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure/tree/main/Instructions/Labs/02#task-2-create-a-mapping-data-flow) - **Enable staging**: Unchecked:

![image](https://user-images.githubusercontent.com/5950304/119149919-f4ddec00-ba1b-11eb-9113-cd7be170086f.png)

Can you please validate this setting?

@VitalyMCT as far as your error goes, are you running inside of your own subscription, or are you using a hosted lab environment?

**Comment by VitalyMCT** [comment] 2021-05-21 16:53
@joelhulen It's the latter: CloudLabs ALH.

**Comment by joelhulen** [comment] 2021-05-21 17:23
@VitalyMCT please follow up with CloudLabs support. I do not have this problem in my own Azure environment. I've also successfully tested this in Spektra's DP-203 environment (https://cloudlabs.ai/). As such, I am unable to reproduce the problem with the environment credentials. You should be able to use the pre-existing linked service for the ADLS Gen2 account, anyway. In the end, staging is not even required for this pipeline run, as I explained in my previous response.

**Comment by VitalyMCT** [comment] 2021-05-21 18:30
@joelhulen Unfortunately it's technically unfeasible to reopen the data flow in Spektra's environment as is gets decommissioned after the lab. So reproducing this issue would require redoing a large portion of the lab.

If it worked for you with the same ALH then the only thing I can think of is that I might've missed the same step that you noted in the response to @Jason-M-Richards. Or something in ADF itself has changed since the last validation.

Regarding: 

> You should be able to use the pre-existing linked service for the ADLS Gen2 account

That was one of the workarounds I've tried before opening this ticket. It did not work due to the permissions the ALH has (for instructors/students) on that data lake storage resource.

**Comment by ctesta-oneillmsft** [comment] 2021-05-28 08:11
Closing as resolved, as step in Exercise 5, Task 2, step 36 addresses this

**Closed by ctesta-oneillmsft** 2021-05-28 08:11 UTC
